Repository cat-in-136/cargo-generate-rpm, pull requests merged in 2023-05, with the labels that each got.

#73 Add --profile command line option
  README.md
  src/build_target.rs
  src/config/file_info.rs
  src/main.rs
Labels: enhancement

#74 Fixed warning displayed for file paths before expansion when `--target` and `--profile` options specified and the file does not exist.
  src/config/file_info.rs
Labels: bug

#79 Replace `rpm-rs` with `rpm` in readme
  README.md
Labels: documentation

#78 use expanded file list when determining reqs
  src/config/mod.rs
Labels: bug
