Repository cat-in-136/cargo-generate-rpm, pull requests merged in 2025-03, with the labels that each got.

#130 Introduce multiple version comparison to dependencies
  README.md
  src/config/mod.rs
Labels: enhancement

#129 fix: bump cargo_toml to 0.21 to fix #128 when building under Rust 202…
  Cargo.toml
Labels: task

#132 Fix bug where empty dependency was added to package in case of no dependency
  src/auto_req/script.rs
Labels: bug
